### ISSUE TITLE
Is it possible to support arm32 devices in the future

### ISSUE THREAD

**Issue by fankes** [canyie/pine#2]
我尝试使用arm64架构可以完美的工作，目前在 使用32位lib的app上无法运行，以后有没有计划继续适配32位的设备呢。
错误如下
`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Redmi/lmipro/lmipro:10/QKQ1.200419.002/20.7.9:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2020-07-14 02:46:29+0800
pid: 12365, tid: 12365, name: e.myapplication  >>> com.example.myapplication <<<
uid: 10631
signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xe2f40072
    r0  d4c954f8  r1  6fefdfcc  r2  d643cbd0  r3  ffacf210
    r4  6fefdfcc  r5  ea9102e6  r6  00000002  r7  14ac2700
    r8  00000000  r9  f0435e00  r10 ffacf2a0  r11 ffacf224
    ip  d643cbd0  sp  ffacf210  lr  eb835bc7  pc  e2f40062

backtrace:
      #00 pc 00000062  [anon:pine codes]
      #01 pc 000d8bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #02 pc 00441bf9  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (art_quick_invoke_stub+248) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #03 pc 000e0f81  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+168) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #04 pc 00215663  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x1dc000) (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+270) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #05 pc 00211857  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x1dc000) (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+738) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #06 pc 00436f6b  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeVirtual+594) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #07 pc 000d3814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #08 pc 001668f4  [anon:dalvik-classes.dex extracted in memory from /data/app/com.example.myapplication-5BGYRmy14FAClbuoA1ADyA==/base.apk] (com.example.myapplication.MainActivity.onCreate+80)
      #09 pc 004371e3  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeVirtual+1226) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #10 pc 000d3814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #11 pc 001a871e  /system/framework/framework.jar (android.app.Activity.performCreate+38)
      #12 pc 004371e3  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeVirtual+1226) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #13 pc 000d3814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #14 pc 001a86de  /system/framework/framework.jar (android.app.Activity.performCreate+2)
      #15 pc 004371e3  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeVirtual+1226) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #16 pc 000d3814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #17 pc 0020bc3a  /system/framework/framework.jar (android.app.Instrumentation.callActivityOnCreate+6)
      #18 pc 004371e3  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeVirtual+1226) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #19 pc 000d3814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #20 pc 001972c4  /system/framework/framework.jar (android.app.ActivityThread.performLaunchActivity+752)
      #21 pc 0043901d  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeDirect+976) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #22 pc 000d3914  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_direct+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #23 pc 00196f42  /system/framework/framework.jar (android.app.ActivityThread.handleLaunchActivity+94)
      #24 pc 004371e3  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeVirtual+1226) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #25 pc 000d3814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #26 pc 0027c88e  /system/framework/framework.jar (android.app.servertransaction.LaunchActivityItem.execute+126)
      #27 pc 004371e3  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeVirtual+1226) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #28 pc 000d3814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #29 pc 0027edda  /system/framework/framework.jar (android.app.servertransaction.TransactionExecutor.executeCallbacks+154)
      #30 pc 004371e3  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeVirtual+1226) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #31 pc 000d3814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #32 pc 0027ed16  /system/framework/framework.jar (android.app.servertransaction.TransactionExecutor.execute+146)
      #33 pc 004371e3  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeVirtual+1226) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #34 pc 000d3814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #35 pc 00195e32  /system/framework/framework.jar (android.app.ActivityThread$H.handleMessage+86)
      #36 pc 004371e3  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeVirtual+1226) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #37 pc 000d3814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #38 pc 00327c12  /system/framework/framework.jar (android.os.Handler.dispatchMessage+38)
      #39 pc 004371e3  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeVirtual+1226) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #40 pc 000d3814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #41 pc 0034cdc6  /system/framework/framework.jar (android.os.Looper.loop+502)
      #42 pc 0043975b  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeStatic+934) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #43 pc 000d3994  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_static+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #44 pc 001a0180  /system/framework/framework.jar (android.app.ActivityThread.main+196)
      #45 pc 001f167f  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x1dc000) (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.5926333900727715245+166) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #46 pc 001f6093  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x1dc000) (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+122) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #47 pc 0042b653  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (artQuickToInterpreterBridge+866) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #48 pc 000dd5a1  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+32) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #49 pc 000d8bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #50 pc 00441d0b  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (art_quick_invoke_static_stub+246) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #51 pc 000e0f95  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+188) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #52 pc 0037e417  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x33f000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #53 pc 0037f905  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x33f000) (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned int)+872) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #54 pc 003299af  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x2ee000) (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+30) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #55 pc 005f97e7  /system/framework/arm/boot.oat (art_jni_trampoline+110) (BuildId: f782c579cee46be788bd56e2d5a7b56f5e17f8e6)
      #56 pc 000d8bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #57 pc 00441bf9  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (art_quick_invoke_stub+248) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #58 pc 000e0f81  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+168) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #59 pc 00215663  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x1dc000) (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+270) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #60 pc 00211857  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x1dc000) (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+738) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #61 pc 00436f6b  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (MterpInvokeVirtual+594) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #62 pc 000d3814  /apex/com.android.runtime/lib/libart.so (mterp_op_invoke_virtual+20) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #63 pc 0039da06  /system/framework/framework.jar (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
      #64 pc 001f167f  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x1dc000) (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.5926333900727715245+166) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #65 pc 001f6093  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x1dc000) (art::interpreter::EnterInterpreterFromEntryPoint(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*)+122) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #66 pc 0042b653  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (artQuickToInterpreterBridge+866) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #67 pc 000dd5a1  /apex/com.android.runtime/lib/libart.so (art_quick_to_interpreter_bridge+32) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #68 pc 01d9b321  /system/framework/arm/boot-framework.oat (com.android.internal.os.ZygoteInit.main+1888) (BuildId: 0764005d9284253165d4e2551608affed4a424ea)
      #69 pc 000d8bc5  /apex/com.android.runtime/lib/libart.so (art_quick_invoke_stub_internal+68) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #70 pc 00441d0b  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x387000) (art_quick_invoke_static_stub+246) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #71 pc 000e0f95  /apex/com.android.runtime/lib/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+188) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #72 pc 0037e417  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x33f000) (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+54) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #73 pc 0037e1b3  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x33f000) (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+290) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #74 pc 002c4ce1  /apex/com.android.runtime/lib/libart.so!libart.so (offset 0x1dc000) (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+492) (BuildId: 5ba25df87c56de8a448a3580e0285d31)
      #75 pc 000876a9  /system/lib/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+28) (BuildId: 3934e44643c43496d7935fce12ef8805)
      #76 pc 00089cd1  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+552) (BuildId: 3934e44643c43496d7935fce12ef8805)
      #77 pc 000023bd  /system/bin/app_process32 (main+880) (BuildId: 1f21cbd943f18cf433c7967ff5199cf0)
      #78 pc 0005ba83  /apex/com.android.runtime/lib/bionic/libc.so (__libc_init+66) (BuildId: ad9864790c4bab27c51eb9dd56fb7b92)
      #79 pc 00002037  /system/bin/app_process32 (_start_main+46) (BuildId: 1f21cbd943f18cf433c7967ff5199cf0)
      #80 pc 000ba5e8  /apex/com.android.runtime/bin/linker!ld-android.so (offset 0x20000) (__dl___aeabi_uidivmod+12) (BuildId: d78666821ca28a26d741b00e89c63a90)
      #81 pc 007fe78e  [stack]
`

**Comment by canyie** [comment]
支持arm32的，这个问题是因为我在本来就是arm32的几台设备上测试没事就忘了在兼容32的64上测试。。

**Comment by canyie** [comment]
0.1.6里修好了
