### ISSUE TITLE
Android 12 crashes / not supported

### ISSUE THREAD

**Issue by vegedreamgagnoa** [canyie/pine#21]
Running Pine hooks resulted in crash

`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 17671`

Any plans to support Android 12 asap?

Seems to be issue with `PineEnhances.enableDelayHook()`. Crashes immediately on Android 12 Google Pixel released/public factory image.

tag @canyie @canyie

**Comment by vegedreamgagnoa** [comment]
@canyie I fixed the classlinker offset to 496; but it didn't help as it only fixes offset mismatch and the app still crashing
Error:
`A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 18986 (vegedreamapp), pid 18986 (vegedreamapp)`

Everytime PineEnhances.enableDelayHook is called, the app crashes on Android 12 public image.
Help needed.

**Comment by vegedreamgagnoa** [comment]
Maybe we need to hook `_ZN3art11ClassLinker22FixupStaticTrampolinesEPNS_6ThreadENS_6ObjPtrINS_6mirror5ClassEEE` here. (`FixupStaticTrampolines`)

@canyie

**Comment by vegedreamgagnoa** [comment]
**[Confirmed issue on Android 12]**: pending hook/delayed hook with PineEnhances.enableDelayHook();

**Comment by vegedreamgagnoa** [comment]
If you need my help in exploring let me know @canyie . Maybe there's some issues with inlining or something. or if we could find another method to hook without directly relying on art structures

**Comment by canyie** [comment]
please attach full log file instead of filtered one
