### ISSUE TITLE
Release后无效

### ISSUE THREAD

**Issue by refgd** [canyie/pine#29]
我在调式的时候hook是有效的，生成正式包后就无效了，请问是什么问题。都是在同一台手机 原生Android 12L，区别只有是否开启debug

**Comment by canyie** [comment]
@refgd 请提供 hook 了哪些方法，以及相关日志。另外可以尝试 adb shell cmd package compile --reset 包名 清除 dex2oat 缓存后再试。

**Comment by canyie** [comment]
一周未回复，当做 issue 已经解决，关闭
