### ISSUE TITLE
有可能实现java 行级代码hook吗？

### ISSUE THREAD

**Issue by coderstory** [canyie/pine#4]
之前写核心破解的时候  pm包里的方法都巨长
但是xposed的api只支持方法级别的hook
导致这些巨长逻辑又巨多的方法很难处理

但是又不想patch smali

**Comment by canyie** [comment]
很难，就算不考虑怎么根据字节码定位具体机器码，方法执行到一半时寄存器和栈上是什么鬼这些都无法预测，很容易就跑飞

**Comment by google-mirror** [comment]
当然有, 不然java debugger是咋实现的

**Comment by canyie** [comment]
@google-mirror debugger是牺牲性能实现的
