### ISSUE TITLE
How to break method call

### ISSUE THREAD

**Issue by kyzsuukii** [canyie/pine#44]
its possible to break method call using pine

example:
```java
public void foo() {
     // code here
}
```
i want to break call `foo` method like add `return-void` in smali
```smali
.method foo()V
     register x
     return-void
    # real code here
.end
```

its force to `return-void` and not execute code inside that method

**Comment by canyie** [comment]
```java
Method target = YourClass.class.getDeclaredMethod("foo");
Pine.hook(target, MethodReplacement.DO_NOTHING);
```

**Comment by rudrakshik** [comment]
> ```java
> Method target = YourClass.class.getDeclaredMethod("foo");
> Pine.hook(target, MethodReplacement.DO_NOTHING);
> ```

Wbat if we hook onCreate and only want to let it load its suoer onCreate method and then break it?

I haven't found a way to call it, can you suggest anything for this?
