### ISSUE TITLE
无法注入系统进程system_server

### ISSUE THREAD

**Issue by dqzg12300** [canyie/pine#46]
在system_server中注入报错如下

09-06 08:09:58.343  2145  2145 W Pine    : Android version too high, not tested now...
09-06 08:09:58.350  2145  2145 I Pine    : Pine native init...
09-06 08:09:58.354  2145  2145 W system_server: type=1400 audit(0.0:6): avc: denied { execmem } for scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=process permissive=0
09-06 08:09:58.354  2145  2145 W system_server: type=1400 audit(0.0:7): avc: denied { execmem } for scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=process permissive=0
09-06 08:09:58.354  2145  2145 W system_server: type=1400 audit(0.0:8): avc: denied { execmem } for scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=process permissive=0
09-06 08:09:58.354  2145  2145 W system_server: type=1400 audit(0.0:9): avc: denied { execmem } for scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=process permissive=0
09-06 08:09:58.355  2145  2145 D Pine    : get module base /apex/com.android.art/lib64/libart.so: 516572577792
09-06 08:09:58.356  2145  2145 E Pine    : mprotect failed for 0x78465c640c: Permission denied (13)
09-06 08:09:58.356  2145  2145 E Pine    : Failed to make target code 0x78465c640c writable!
09-06 08:09:58.356  2145  2145 E Pine    : mprotect failed for 0x78465c7684: Permission denied (13)
09-06 08:09:58.356  2145  2145 E Pine    : Failed to make target code 0x78465c7684 writable!
09-06 08:09:58.356  2145  2145 E Pine    : mprotect failed for 0x78465c5e70: Permission denied (13)
09-06 08:09:58.356  2145  2145 E Pine    : Failed to make target code 0x78465c5e70 writable!
09-06 08:09:58.357  2145  2145 E Pine    : mprotect failed for 0x78465c61bc: Permission denied (13)
09-06 08:09:58.357  2145  2145 E Pine    : Failed to make target code 0x78465c61bc writable!
09-06 08:09:58.375  2145  2145 D Pine    : get module base /apex/com.android.art/lib64/libart-compiler.so: 516253810688
09-06 08:09:58.399  2145  2145 W Pine    : JavaVM offset mismatches the default offset, try search the memory of Runtime
09-06 08:09:58.399  2145  2145 W Pine    : Found JavaVM in Runtime at 688
09-06 08:09:58.399  2145  2145 I Pine    : Got class linker 0x792b0daeb0
09-06 08:09:58.400  2145  2145 W system_server: type=1400 audit(0.0:10): avc: denied { execmem } for scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=process permissive=0
09-06 08:09:58.402  2145  2145 E Pine    : Unable to allocate executable memory: Permission denied (13)
09-06 08:09:58.402  2145  2145 E Pine    : Failed to allocate bridge jump trampoline!
09-06 08:09:58.402  2145  2145 E Pine    : Failed to install replacement trampoline on method 0x783873d3d8: Permission denied (13). This is a security failure, check selinux policy, seccomp or capabilities. Earlier log may point out root cause.

**Comment by dqzg12300** [comment]
已解决，selinux权限问题。

**Comment by wj2008** [comment]
allow zygote self:process execmem;
