### ISSUE TITLE
log.so冲突

### ISSUE THREAD

**Issue by Thehepta** [canyie/pine#49]
after importing the pine libray,I am unable to use the log in my NDK project.The reason is tha pine has already used the log library . If i use it agin.it may cause conpliation conflicts and fail to compile successfully .How can i solve this problem

**Comment by allenjq** [comment]
排除一个就行
'''packagingOptions {
        {
            exclude'lib/armeabi-v7a/liblog.so'
        }
    }
'''

**Comment by allenjq** [comment]
排除一个就可以了
`packagingOptions {
        {
            exclude'lib/armeabi-v7a/liblog.so'
        }
    }`
