### ISSUE TITLE
根据条件忽略method

### ISSUE THREAD

**Issue by Ulez** [canyie/pine#55]
beforeCall和beforeCall，还有其他能实现吗？比如满足条件执行原始的method，不满足直接return忽略这个method。

**Comment by canyie** [comment]
需要跳过原方法执行的话，在 beforeCall 内调用 callFrame.setResult 设置返回值或 callFrame.setThrowable 设置异常即可。对于 void 方法，设置 null 返回值即可。

**Comment by Ulez** [comment]
> 需要跳过原方法执行的话，在 beforeCall 内调用 callFrame.setResult 设置返回值或 callFrame.setThrowable 设置异常即可。对于 void 方法，设置 null 返回值即可。

感谢作者回复，前面我研究了下可以通过MethodReplacement实现，您回复的这种更加精简，谢谢
