### ISSUE TITLE
小米14澎湃系统异常 Unreadable

### ISSUE THREAD

**Issue by 9c-x** [canyie/pine#60]
![image](https://github.com/canyie/pine/assets/31823312/1a293657-5feb-4f78-9d08-283834ee1a8b)

**Comment by canyie** [comment]
你这个借图一没截到 Fatal signal，二是你的 lib 是自己释放到私有文件夹的，debugger 读不了，没有符号我根本看不出哪里有问题
可以试一下编译自带的 app 运行，有问题再发出来

**Comment by 9c-x** [comment]
> 你这个借图一没截到 Fatal signal，二是你的 lib 是自己释放到私有文件夹的，debugger 读不了，没有符号我根本看不出哪里有问题 可以试一下编译自带的 app 运行，有问题再发出来

小米14就是放在了私有文件夹下面了
