### ISSUE TITLE
Release包有可能会hook失败

### ISSUE THREAD

**Issue by Lok1n8** [canyie/pine#64]
Galaxy Z Flip4
Android13
Pine029
使用代码为
[
![企业微信20240327-111312](https://github.com/canyie/pine/assets/23357769/37d80635-00a1-403d-870b-cef2df021e64)
](url)

这个现象就很抽象。我打了一个Release的包，重复（安装和删除）这个流程。 有时候会Hook成功 有时候Hook会失败
失败时候的日志为
![企业微信20240327-152104](https://github.com/canyie/pine/assets/23357769/372fc59b-ac66-478e-b0c7-e96104b88cbd)

**Comment by sher-loki** [comment]
adb shell cmd package compile --reset 这个我也试过 但是报错 Exception occurred while executing 'compile':
java.lang.SecurityException: Only the system can clear all profile data

**Comment by sher-loki** [comment]
我又测了一下 好像是安装之后 你不理他 过一会再点开就会触发
![Uploading 企业微信20240327-152104.png…]()

**Comment by canyie** [comment]
这种问题很可能就是被 inline 了，这个实际上没办法解决，如果已知调用者的话可以调用 Pine.decompile() 提前 deoptimize 调用它的方法。
