### ISSUE TITLE
安装的时候编译不通过在nexus6P 8.1和xiaomi mix3上

### ISSUE THREAD

**Issue by hetianlong0** [canyie/pine#7]
Build command failed.
Error while executing process D:\android-tools\sdk\cmake\3.10.2.4988404\bin\ninja.exe with arguments {-C D:\tmp\tmp-test2\pine-master\core\.cxx\cmake\debug\arm64-v8a pine}
ninja: Entering directory `D:\tmp\tmp-test2\pine-master\core\.cxx\cmake\debug\arm64-v8a'
[1/1] Linking CXX shared library libpine.so
FAILED: libpine.so 
cmd.exe /C "cd . && D:\android-tools\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android21 --gcc-toolchain=D:/android-tools/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/android-tools/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -std=c++17 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libpine.so -o libpine.so CMakeFiles/pine.dir/pine.cpp.o CMakeFiles/pine.dir/ruler.cpp.o CMakeFiles/pine.dir/android.cpp.o CMakeFiles/pine.dir/jni_bridge.cpp.o CMakeFiles/pine.dir/art/art_method.cpp.o CMakeFiles/pine.dir/art/thread.cpp.o CMakeFiles/pine.dir/art/jit.cpp.o CMakeFiles/pine.dir/trampoline/trampoline_installer.cpp.o CMakeFiles/pine.dir/utils/memory.cpp.o CMakeFiles/pine.dir/utils/scoped_memory_access_protection.cpp.o CMakeFiles/pine.dir/utils/elf_img.cpp.o CMakeFiles/pine.dir/utils/well_known_classes.cpp.o CMakeFiles/pine.dir/trampoline/arch/arm64.cpp.o CMakeFiles/pine.dir/trampoline/arch/arm64.S.o  -llog -latomic -lm && cd ."
ld: error: relocation R_AARCH64_LD_PREL_LO19 cannot be used against symbol pine_direct_jump_trampoline_jump_entry; recompile with -fPIC
>>> defined in CMakeFiles/pine.dir/trampoline/arch/arm64.S.o
>>> referenced by CMakeFiles/pine.dir/trampoline/arch/arm64.S.o:(.data+0x0)

ld: error: relocation R_AARCH64_LD_PREL_LO19 cannot be used against symbol pine_bridge_jump_trampoline_target_method; recompile with -fPIC
>>> defined in CMakeFiles/pine.dir/trampoline/arch/arm64.S.o
>>> referenced by CMakeFiles/pine.dir/trampoline/arch/arm64.S.o:(.data+0x10)

ld: error: relocation R_AARCH64_LD_PREL_LO19 cannot be used against symbol pine_bridge_jump_trampoline_extras; recompile with -fPIC
>>> defined in CMakeFiles/pine.dir/trampoline/arch/arm64.S.o
>>> referenced by CMakeFiles/pine.dir/trampoline/arch/arm64.S.o:(.data+0x1C)

ld: error: relocation R_AARCH64_LD_PREL_LO19 cannot be used against symbol pine_bridge_jump_trampoline_bridge_method; recompile with -fPIC
>>> defined in CMakeFiles/pine.dir/trampoline/arch/arm64.S.o
>>> referenced by CMakeFiles/pine.dir/trampoline/arch/arm64.S.o:(.data+0x50)

ld: error: relocation R_AARCH64_LD_PREL_LO19 cannot be used against symbol pine_bridge_jump_trampoline_bridge_entry; recompile with -fPIC
>>> defined in CMakeFiles/pine.dir/trampoline/arch/arm64.S.o
>>> referenced by CMakeFiles/pine.dir/trampoline/arch/arm64.S.o:(.data+0x54)

ld: error: relocation R_AARCH64_LD_PREL_LO19 cannot be used against symbol pine_bridge_jump_trampoline_call_origin_entry; recompile with -fPIC
>>> defined in CMakeFiles/pine.dir/trampoline/arch/arm64.S.o
>>> referenced by CMakeFiles/pine.dir/trampoline/arch/arm64.S.o:(.data+0x5C)

ld: error: relocation R_AARCH64_LD_PREL_LO19 cannot be used against symbol pine_call_origin_trampoline_origin_method; recompile with -fPIC
>>> defined in CMakeFiles/pine.dir/trampoline/arch/arm64.S.o
>>> referenced by CMakeFiles/pine.dir/trampoline/arch/arm64.S.o:(.data+0x90)

ld: error: relocation R_AARCH64_LD_PREL_LO19 cannot be used against symbol pine_call_origin_trampoline_origin_code_entry; recompile with -fPIC
>>> defined in CMakeFiles/pine.dir/trampoline/arch/arm64.S.o
>>> referenced by CMakeFiles/pine.dir/trampoline/arch/arm64.S.o:(.data+0x94)

ld: error: relocation R_AARCH64_LD_PREL_LO19 cannot be used against symbol pine_backup_trampoline_origin_method; recompile with -fPIC
>>> defined in CMakeFiles/pine.dir/trampoline/arch/arm64.S.o
>>> referenced by CMakeFiles/pine.dir/trampoline/arch/arm64.S.o:(.data+0xB0)

ld: error: relocation R_AARCH64_LD_PREL_LO19 cannot be used against symbol pine_backup_trampoline_remaining_code_entry; recompile with -fPIC
>>> defined in CMakeFiles/pine.dir/trampoline/arch/arm64.S.o
>>> referenced by CMakeFiles/pine.dir/trampoline/arch/arm64.S.o:(.data+0xCC)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by canyie** [comment]
换ndk版本

**Comment by Ahren-Li** [comment]
@canyie 大佬用的哪个NDK版本，我需要在Android11上用。

**Comment by canyie** [comment]
@Ahren-Li 我用的 21
