### ISSUE TITLE
My Device

### ISSUE THREAD

**Issue by Wadaaak** [canyie/pine#84]

**Comment by Wadaaak** [comment]
![Screenshot_20241215-003001](https://github.com/user-attachments/assets/f37a778d-4825-46df-a023-2d82eb5981a6)


> _No description provided._

Someone gathering my personal information and controlling the software of my device

**Comment by canyie** [comment]
Hello, sorry but we are unable to help you with this issue. I suggest you call police, contact Google account support, or seek help from your device manufacturer instead.
